"""Canonical discovery targets for an Asia-focused LPG trading cockpit.

These are semantic targets, not guessed Platts symbols.  The Excel discovery
workflow maps entitled symbols to these stable keys and records anything not
licensed as an explicit entitlement state.
"""

from typing import Any, Dict, Tuple


def _candidate(
    key: str,
    name: str,
    product: str,
    market: str,
    location: str,
    basis: str,
    delivery_type: str,
    priority: int,
    *search_terms: str,
    region: str = "Asia",
    currency: str = "USD",
    unit: str = "mt",
    family: str = "price",
    summary: bool = False,
) -> Dict[str, Any]:
    return {
        "candidate_id": key.lower(),
        "canonical_key": key,
        "family": family,
        "name": name,
        "product": product,
        "market": market,
        "region": region,
        "location": location,
        "basis": basis,
        "delivery_type": delivery_type,
        "expected_currency": currency,
        "expected_unit": unit,
        "priority": priority,
        "summary": summary,
        "search_terms": list(search_terms),
    }


ASIA_LPG_CANDIDATES: Tuple[Dict[str, Any], ...] = (
    _candidate("FEI_PROPANE", "CFR North Asia Propane (FEI)", "Propane",
               "CFR North Asia", "North Asia", "CFR", "physical", 10,
               "CFR North Asia propane", "FEI propane", summary=True),
    _candidate("CFR_NA_BUTANE", "CFR North Asia Butane", "Butane",
               "CFR North Asia", "North Asia", "CFR", "physical", 20,
               "CFR North Asia butane", "FEI butane", summary=True),
    _candidate("CP_PROPANE", "Saudi Aramco Contract Price Propane", "Propane",
               "Saudi CP", "Saudi Arabia", "FOB", "monthly", 30,
               "Saudi CP propane", "contract price propane", summary=True,
               region="Middle East"),
    _candidate("CP_BUTANE", "Saudi Aramco Contract Price Butane", "Butane",
               "Saudi CP", "Saudi Arabia", "FOB", "monthly", 40,
               "Saudi CP butane", "contract price butane", summary=True,
               region="Middle East"),
    _candidate("FOB_AG_PROPANE", "FOB Arab Gulf Propane", "Propane",
               "FOB Arab Gulf", "Arab Gulf", "FOB", "physical", 50,
               "FOB Arab Gulf propane", "FOB AG propane", summary=True,
               region="Middle East"),
    _candidate("FOB_AG_BUTANE", "FOB Arab Gulf Butane", "Butane",
               "FOB Arab Gulf", "Arab Gulf", "FOB", "physical", 60,
               "FOB Arab Gulf butane", "FOB AG butane",
               region="Middle East"),
    _candidate("CFR_EAST_CHINA_PROPANE", "CFR East China Propane", "Propane",
               "CFR East China", "East China", "CFR", "physical", 70,
               "CFR East China propane", summary=True),
    _candidate("CFR_EAST_CHINA_BUTANE", "CFR East China Butane", "Butane",
               "CFR East China", "East China", "CFR", "physical", 80,
               "CFR East China butane"),
    _candidate("CFR_SOUTH_CHINA_PROPANE", "CFR South China Propane", "Propane",
               "CFR South China", "South China", "CFR", "physical", 90,
               "CFR South China propane"),
    _candidate("CFR_SOUTH_CHINA_BUTANE", "CFR South China Butane", "Butane",
               "CFR South China", "South China", "CFR", "physical", 100,
               "CFR South China butane"),
    _candidate("CFR_JAPAN_PROPANE", "CFR Japan Propane", "Propane",
               "CFR Japan", "Japan", "CFR", "physical", 110,
               "CFR Japan propane"),
    _candidate("CFR_JAPAN_BUTANE", "CFR Japan Butane", "Butane",
               "CFR Japan", "Japan", "CFR", "physical", 120,
               "CFR Japan butane"),
    _candidate("CFR_PHILIPPINES_LPG", "CFR Philippines LPG", "Mixed LPG",
               "CFR Philippines", "Philippines", "CFR", "pressurized", 130,
               "CFR Philippines LPG", "pressurized LPG Philippines"),
    _candidate("CFR_VIETNAM_LPG", "CFR Vietnam LPG", "Mixed LPG",
               "CFR Vietnam", "Vietnam", "CFR", "pressurized", 140,
               "CFR Vietnam LPG", "pressurized LPG Vietnam"),
    _candidate("CFR_SINGAPORE_LPG", "CFR Singapore LPG", "Mixed LPG",
               "CFR Singapore", "Singapore", "CFR", "pressurized", 150,
               "CFR Singapore LPG", "pressurized LPG Singapore"),
    _candidate("FOB_SINGAPORE_LPG", "FOB Singapore LPG", "Mixed LPG",
               "FOB Singapore", "Singapore", "FOB", "pressurized", 160,
               "FOB Singapore LPG", "pressurized LPG Singapore"),
    _candidate("FEI_PROPANE_M1", "FEI Propane M+1", "Propane",
               "CFR North Asia Forward", "North Asia", "CFR", "forward", 170,
               "FEI propane M1", "CFR North Asia propane forward", family="curve"),
    _candidate("FEI_PROPANE_M2", "FEI Propane M+2", "Propane",
               "CFR North Asia Forward", "North Asia", "CFR", "forward", 180,
               "FEI propane M2", family="curve"),
    _candidate("FEI_PROPANE_M3", "FEI Propane M+3", "Propane",
               "CFR North Asia Forward", "North Asia", "CFR", "forward", 190,
               "FEI propane M3", family="curve"),
    _candidate("MB_PROPANE_USD_MT", "Mont Belvieu Propane USD/mt", "Propane",
               "Mont Belvieu", "Texas", "FOB", "physical", 200,
               "Mont Belvieu propane USD mt", "non-LST propane", summary=True,
               region="North America"),
    _candidate("MB_BUTANE_USD_MT", "Mont Belvieu Normal Butane USD/mt", "Butane",
               "Mont Belvieu", "Texas", "FOB", "physical", 210,
               "Mont Belvieu normal butane USD mt", region="North America"),
    _candidate("MOPJ_NAPHTHA", "Mean of Platts Japan Naphtha", "Naphtha",
               "CFR Japan", "Japan", "CFR", "physical", 220,
               "MOPJ naphtha", "CFR Japan naphtha", summary=True),
    _candidate("VLGC_AG_JAPAN", "VLGC Freight Ras Tanura to Chiba", "Freight",
               "VLGC Arab Gulf-Japan", "Ras Tanura/Chiba", "voyage", "freight", 230,
               "VLGC Ras Tanura Chiba", "LPG freight AG Japan", family="freight",
               summary=True),
    _candidate("VLGC_USGC_NA", "VLGC Freight USGC to North Asia", "Freight",
               "VLGC USGC-North Asia", "Houston/Chiba", "voyage", "freight", 240,
               "VLGC Houston Chiba", "LPG freight USGC Asia", family="freight",
               summary=True),
    _candidate("EWINDOW_LPG_TRADES", "Asia LPG eWindow Trades", "LPG",
               "Platts eWindow", "Asia", "MOC", "transaction", 250,
               "eWindow LPG trades", "MOC LPG trades", currency="", unit="",
               family="ewindow"),
    _candidate("EWINDOW_LPG_BIDS_OFFERS", "Asia LPG eWindow Bids and Offers", "LPG",
               "Platts eWindow", "Asia", "MOC", "order", 260,
               "eWindow LPG bids offers", "MOC LPG", currency="", unit="",
               family="ewindow"),
    _candidate("CP_PROPANE_M1", "Saudi CP Propane Swap M+1", "Propane",
               "Saudi CP Forward", "Singapore", "swap", "forward", 270,
               "Propane Saudi CP Swap Mo01", family="curve"),
    _candidate("CP_PROPANE_M2", "Saudi CP Propane Swap M+2", "Propane",
               "Saudi CP Forward", "Singapore", "swap", "forward", 280,
               "Propane Saudi CP Swap Mo02", family="curve"),
    _candidate("CP_PROPANE_M3", "Saudi CP Propane Swap M+3", "Propane",
               "Saudi CP Forward", "Singapore", "swap", "forward", 290,
               "Propane Saudi CP Swap Mo03", family="curve"),
    *tuple(
        _candidate(key, name, product, "CFR North Asia Half-Month", "North Asia",
                   "CFR", "half_month", priority, search, family="curve")
        for key, name, product, priority, search in (
            ("FEI_PROPANE_HM1", "CFR North Asia Propane Half-Month 1", "Propane", 300, "CFR North Asia propane first half-month"),
            ("FEI_PROPANE_HM2", "CFR North Asia Propane Half-Month 2", "Propane", 310, "CFR North Asia propane second half-month"),
            ("FEI_PROPANE_HM3", "CFR North Asia Propane Half-Month 3", "Propane", 320, "CFR North Asia propane third half-month"),
            ("CFR_NA_BUTANE_HM1", "CFR North Asia Butane Half-Month 1", "Butane", 330, "CFR North Asia butane first half-month"),
            ("CFR_NA_BUTANE_HM2", "CFR North Asia Butane Half-Month 2", "Butane", 340, "CFR North Asia butane second half-month"),
            ("CFR_NA_BUTANE_HM3", "CFR North Asia Butane Half-Month 3", "Butane", 350, "CFR North Asia butane third half-month"),
        )
    ),
    _candidate("CFR_NA_LPG_1111", "CFR North Asia LPG 11:11", "Mixed LPG",
               "CFR North Asia", "North Asia", "CFR", "physical", 360,
               "CFR North Asia refrigerated LPG 11:11"),
    _candidate("FOB_AG_PROPANE_CP_DIFF", "FOB Arab Gulf Propane vs Saudi CP", "Propane",
               "FOB Arab Gulf Differential", "Arab Gulf", "FOB", "differential", 370,
               "Propane FOB AG differential Saudi CP", family="spread", region="Middle East"),
    _candidate("FOB_AG_BUTANE_CP_DIFF", "FOB Arab Gulf Butane vs Saudi CP", "Butane",
               "FOB Arab Gulf Differential", "Arab Gulf", "FOB", "differential", 380,
               "Butane FOB AG differential Saudi CP", family="spread", region="Middle East"),
    _candidate("FOB_EAST_CHINA_LPG", "FOB East China LPG", "Mixed LPG",
               "FOB East China", "East China", "FOB", "pressurized", 390,
               "LPG FOB East China"),
    _candidate("FOB_EAST_CHINA_CP_DIFF", "FOB East China LPG vs Saudi CP", "Mixed LPG",
               "FOB East China Differential", "East China", "FOB", "differential", 400,
               "LPG FOB East China premium Saudi CP", family="spread"),
    _candidate("FOB_SINGAPORE_CP_DIFF", "FOB Singapore LPG vs Saudi CP", "Mixed LPG",
               "FOB Singapore Differential", "Singapore", "FOB", "differential", 410,
               "LPG FOB Singapore premium Saudi CP", family="spread"),
    _candidate("PRESSURIZED_ASIA_PROPANE", "Pressurized Asia Propane", "Propane",
               "Pressurized Asia", "Asia", "CFR", "pressurized", 420,
               "Propane pressurized Asia"),
    _candidate("MB_PROPANE_ENTERPRISE_USC_GAL", "Mont Belvieu Enterprise Propane", "Propane",
               "Mont Belvieu", "Texas", "FOB", "forward", 430,
               "Propane Enterprise Mt Belvieu Mo01", region="North America",
               currency="USC", unit="gal"),
    _candidate("MB_PROPANE_ET_USC_GAL", "Mont Belvieu Energy Transfer Propane", "Propane",
               "Mont Belvieu", "Texas", "FOB", "forward", 440,
               "Propane Energy Transfer Mt Belvieu Mo01", region="North America",
               currency="USC", unit="gal"),
    _candidate("MB_BUTANE_ENTERPRISE_USC_GAL", "Mont Belvieu Enterprise Butane", "Butane",
               "Mont Belvieu", "Texas", "FOB", "forward", 450,
               "Butane Enterprise Mt Belvieu Mo01", region="North America",
               currency="USC", unit="gal"),
    _candidate("MB_BUTANE_ET_USC_GAL", "Mont Belvieu Energy Transfer Butane", "Butane",
               "Mont Belvieu", "Texas", "FOB", "forward", 460,
               "Butane Energy Transfer Mt Belvieu", region="North America",
               currency="USC", unit="gal"),
    _candidate("FOB_USGC_LPG_2222", "LPG 22:22 FOB US Gulf Coast", "Mixed LPG",
               "FOB USGC", "US Gulf Coast", "FOB", "physical", 470,
               "LPG 22:22 FOB USGC", region="North America"),
    _candidate("CURVE_CP_PROPANE", "Saudi CP Propane Forward Curve", "Propane",
               "Saudi CP Derivatives", "Singapore", "swap", "forward_curve", 480,
               "Saudi CP propane derivatives", family="curve"),
    _candidate("CURVE_FEI_PROPANE", "CFR North Asia Propane Forward Curve", "Propane",
               "CFR North Asia Derivatives", "Singapore", "swap", "forward_curve", 490,
               "CFR North Asia propane derivatives", family="curve"),
    _candidate("CURVE_FEI_CP_PROPANE", "FEI - Saudi CP Propane Forward Curve", "Propane",
               "FEI-CP Derivatives", "Singapore", "swap", "forward_curve", 500,
               "CFR North Asia FOB Saudi CP propane derivatives", family="curve"),
    _candidate("CURVE_FEI_MOPJ", "FEI Propane - MOPJ Forward Curve", "Propane/Naphtha",
               "FEI-MOPJ Derivatives", "Singapore", "swap", "forward_curve", 510,
               "CFR North Asia propane versus naphtha MOPJ", family="curve"),
    _candidate("EWINDOW_AMERICAS_LPG_TRADES", "Americas LPG eWindow Trades", "LPG",
               "Platts eWindow", "Americas", "MOC", "transaction", 520,
               "eWindow Americas LPG trades", currency="", unit="", family="ewindow",
               region="North America"),
)


# Coefficients are applied to normalized values.  Definitions deliberately do
# not attempt hidden unit conversion: the service blocks incompatible legs.
DEFAULT_SPREADS: Tuple[Dict[str, Any], ...] = (
    {
        "id": "fei_cp_propane",
        "name": "FEI Propane - Saudi CP Propane",
        "legs": (("FEI_PROPANE", 1.0), ("CP_PROPANE", -1.0)),
        "alignment": "contract_month",
    },
    {
        "id": "fei_cp_butane",
        "name": "CFR North Asia Butane - Saudi CP Butane",
        "legs": (("CFR_NA_BUTANE", 1.0), ("CP_BUTANE", -1.0)),
        "alignment": "contract_month",
    },
    {
        "id": "north_asia_pb",
        "name": "North Asia Propane - Butane",
        "legs": (("FEI_PROPANE", 1.0), ("CFR_NA_BUTANE", -1.0)),
    },
    {
        "id": "fei_mopj",
        "name": "FEI Propane - MOPJ Naphtha",
        "legs": (("FEI_PROPANE", 1.0), ("MOPJ_NAPHTHA", -1.0)),
    },
    {
        "id": "fei_mb_gross",
        "name": "FEI Propane - Mont Belvieu Propane",
        "legs": (("FEI_PROPANE", 1.0), ("MB_PROPANE_USD_MT", -1.0)),
    },
    {
        "id": "fei_mb_arb_net",
        "name": "FEI - Mont Belvieu - USGC/Asia Freight",
        "legs": (
            ("FEI_PROPANE", 1.0),
            ("MB_PROPANE_USD_MT", -1.0),
            ("VLGC_USGC_NA", -1.0),
        ),
    },
    {
        "id": "ag_na_propane",
        "name": "FEI Propane - FOB Arab Gulf Propane",
        "legs": (("FEI_PROPANE", 1.0), ("FOB_AG_PROPANE", -1.0)),
    },
)
